subgraphs:
  localspellbook:
    routing_url: http://localhost:4000/graphql
    schema:
      file: ./localspellbook.graphql
  5edndapi:
    routing_url: https://www.dnd5eapi.co/graphql
    schema:
      file: ./5edndschema.graphql
